---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apimmgmt.no.malvik
  resources:
  - apimservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apimmgmt.no.malvik
  resources:
  - apimservices/finalizers
  verbs:
  - update
- apiGroups:
  - apimmgmt.no.malvik
  resources:
  - apimservices/status
  verbs:
  - get
  - patch
  - update
