apiVersion: apimmgmt.no.malvik/v1
kind: ApimService
metadata:
  labels:
    app.kubernetes.io/name: apimservice
    app.kubernetes.io/instance: apimservice-instance
    app.kubernetes.io/part-of: apimops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: apimops
  name: apimservice
spec:
  apiId: "ConfDemo2"
  apiPath: "conf"
  apiUrl: "https://conferenceapi.azurewebsites.net"
